Constants =
  #Exercise Actions
  EXERCISE_LOAD: 'EXERCISE_LOAD'
  EXERCISE_LOADED: 'EXERCISE_LOADED'
  ERROR_LOAD_EXERCISE: 'ERROR_LOAD_EXERCISE'

  EXERCISE_SAVE: 'EXERCISE_SAVE'
  EXERCISE_SAVED: 'EXERCISE_SAVED'
  EXERCISE_SAVE_ERROR: 'EXERCISE_SAVE_ERROR'

  EXERCISE_PUBLISH: 'EXERCISE_SAVE'
  EXERCISE_PUBLISHED: 'EXERCISE_SAVED'
  EXERCISE_PUBLISH_ERROR: 'EXERCISE_PUBLISH_ERROR'

  UPDATE_EXERCISE_STIMULUS: 'EX_UPDATE_STIMULUS'

  #Question Actions
  UPDATE_QUESTION_STIMULUS: 'UPDATE_QUESTION_STIMULUS'
  UPDATE_QUESTION_STEM: 'UPDATE_QUESTION_STEM'
  UPDATE_SOLUTION: 'UPDATE_SOLUTION'
  ADD_ANSWER: 'ADD_ANSWER'
  REMOVE_ANSWER: 'REMOVE_ANSWER'
  MOVE_ANSWER: 'MOVE_ANSWER'
  TOGGLE_MULTIPLE_CHOICE: 'TOGGLE_MULTIPLE_CHOICE'
  TOGGLE_FREE_RESPONSE: 'TOGGLE_FREE_RESPONSE'
  TOGGLE_PRESERVE_ORDER: 'TOGGLE_PRESERVE_ORDER'

  #Answer Actions
  UPDATE_ANSWER_FEEDBACK: 'UPDATE_ANSWER_FEEDBACK'
  UPDATE_ANSWER_CONTENT: 'UPDATE_ANSWER_CONTENT'
  SET_INCORRECT: 'SET_INCORRECT'
  SET_CORRECT: 'SET_CORRECT'

  #Tag Actions
  UPDATE_EDITABLE_TAGS: 'UPDATE_EDITABLE_TAGS'
  UPDATE_FIXED_TAGS: 'UPDATE_FIXED_TAGS'

  #Attachment Actions
  UPLOADED_ATTACHMENT: 'UPLOADED_ATTACHMENT'

  DELETE_ATTACHMENT: 'DELETE_ATTACHMENT'
  DELETED_ATTACHMENT: 'DELETED_ATTACHMENT'
  ERROR_DELETE_ATTACHMENT: 'ERROR_DELETE_ATTACHMENT'

module.exports = Constants
